### ISSUE TITLE
[Regular user] [Creare cont] Creeaza cont nou from the login page launches the existing account dashboard after Back button is pressed

### ISSUE THREAD

**Issue by monikozi** [code4romania/bursa-binelui#118]
**Intra in cont** with existing credentials
From the Dashboard page click **Back**
In the login from, click **Creeaza cont nou**
**Expected result**: The new account form to be displayed
**Actual result:** The user lands back in the existing account dashboard

https://github.com/code4romania/bursa-binelui/assets/64305252/11cb1a1e-5363-4c90-8df7-99188cf70175

**Comment by andreiio** [comment]
Going back in the browser doesn't log the user out, so this is expected behavior.

We can instead prevent the login form from being shown when going back.
