### ISSUE TITLE
[Regular user] [Acc settings] Layout adjustment on mobile display

### ISSUE THREAD

**Issue by monikozi** [code4romania/bursa-binelui#130]
The Setari cont page needs layout adjustments for mobile displays (margins to the left and right)
[https://bursa-binelui.staging.heroesof.tech/profile](url)
![image](https://github.com/code4romania/bursa-binelui/assets/64305252/f6bb0f0b-5de7-44c4-aab7-c0b326d1a1ab)

**Comment by FlorinZarafu** [comment]
fixed in previous coomits

**Comment by FlorinZarafu** [comment]
fixed in previous commits

**Comment by monikozi** [comment]
works as expected on retest
