### ISSUE TITLE
[Admin BB] [Organizatii] Status inconsistency

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/bursa-binelui#201]
**How it should work**: According to [Figma](https://www.figma.com/file/FuZ3rjuQRDaA4Ki5iJadz6/Bursa-Binelui?type=design&node-id=1053%3A33247&mode=design&t=lTR0KTut9EIPBZbl-1), the registration requests coming from organizations can be either approved or rejected. Once a request was approved, the status for the organization can only be changed in deactivated (and for the rejected ones in activated). 

**How it works now:** If i approve/reject an organization I can still approve/dissaprove it and the actions available do not change based on the status of the organization.

**Comment by monikozi** [comment]
It would be nice to disable the option which is not possible (_respinge_ for rejected and _aproba_ for approved items)
Also, the icons next to the action labels are superfluous

**Comment by gheorghelupu17** [comment]
close in [d217edf](https://github.com/code4romania/bursa-binelui/commit/d217edf8a7926afba8a0f6c8a50d4fea639a8409)
