### ISSUE TITLE
[BB Admin] [Organizatii] The layout of the NGOs list is not consistent with the design in Figma

### ISSUE THREAD

**Issue by monikozi** [code4romania/bursa-binelui#219]
In Figma:
- the page is presented in 3 sections, each with the relevant title. 
- there's also a search functionality
- there should also be a _Descarca tabel_ button
![image](https://github.com/code4romania/bursa-binelui/assets/64305252/a675cabc-11da-40bb-a245-da71e8f3c168)

In the current implementation, the list can be filtered by organisation status
- the title of the table does not change - but the filters are visible
- the search functionality is not implemented
- export table is not present
![image](https://github.com/code4romania/bursa-binelui/assets/64305252/8856e855-fbd9-4f93-a291-4276a8fede8e)

**Comment by gheorghelupu17** [comment]
close in [d217edf](https://github.com/code4romania/bursa-binelui/commit/d217edf8a7926afba8a0f6c8a50d4fea639a8409)
we are constraind by filament framework
