### ISSUE TITLE
[BB Admin] [Organizatii] NGO status icons in the table are very confusing

### ISSUE THREAD

**Issue by monikozi** [code4romania/bursa-binelui#220]
**Overlaps issue #210** 

The three status icons are very confusing
Please reconsider the design. One option would be to use a red-amber-green dot system. And include a tooltip when hovering each icon
![image](https://github.com/code4romania/bursa-binelui/assets/64305252/a1a927d6-faf0-4781-8250-5da276bc13c0)

**Comment by gheorghelupu17** [comment]
close in [d217edf](https://github.com/code4romania/bursa-binelui/commit/d217edf8a7926afba8a0f6c8a50d4fea639a8409)
