### ISSUE TITLE
Add newslatter column to users tabel

### ISSUE THREAD

**Issue by gheorghelupu17** [code4romania/bursa-binelui#307]
**Is your feature request related to a problem? Please describe.**
We need to export users who are subscribed to the newsletter 

**Describe the solution you'd like**
A bool column in the user's table that is true if the user check-in registration page to subscribe to the newsletter 

**Additional context**

app/Http/Controllers/Auth/RegisteredUserController.php:69

**Comment by alexPopaCode4** [comment]
#308
