### ISSUE TITLE
(critical bug) Register a project prompts login modal even if user is already logged in

### ISSUE THREAD

**Issue by overeha** [code4romania/bursa-binelui#44]
I went to the Championship page and clicked on "Propune un proiect" and the platform prompted me to login again. I am already logged in. 

<img width="1497" alt="Screenshot 2023-06-25 at 17 26 00" src="https://github.com/code4romania/bursa-binelui/assets/45068169/f2f09e66-cd59-4bd6-8d6a-2c85c27c73bc">

**Comment by gheorghelupu17** [comment]
fixed in championship commit
