### ISSUE TITLE
Register/Login/Forgot password pages - picture and the rest of the content (in the left container) don't align nicely

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/bursa-binelui#60]
https://bursa-binelui.staging.heroesof.tech/register

buttons in 2., and 3, don't align well
picture in 4. has a bigger size (should stay the same through all steps of the form)

1. ![image](https://github.com/code4romania/bursa-binelui/assets/95479576/dd32d34b-e571-4e7b-800a-14e4f7bc0c7d)
2. ![image](https://github.com/code4romania/bursa-binelui/assets/95479576/0684126d-64b8-4aa3-b109-aec93e6b4bda)
3. 
![image](https://github.com/code4romania/bursa-binelui/assets/95479576/e6b905da-fa1c-47d8-91ba-63be8495f2b0)
4. 
![image](https://github.com/code4romania/bursa-binelui/assets/95479576/b63d4c74-6fb3-47fb-8aec-6e13166f3eee)

**Comment by FlorinZarafu** [comment]
Was fixed in [fix](https://github.com/code4romania/bursa-binelui/commit/45e879562086a00f0d4ba014d2fd59143629549d) https://github.com/code4romania/bursa-binelui/issues/60
