### ISSUE TITLE
[Login page] "creeaza cont nou" not active

### ISSUE THREAD

**Issue by avasi-code4ro** [code4romania/bursa-binelui#64]
https://bursa-binelui.staging.heroesof.tech/login

- If you click on "Creeaza cont nou" nothing happens. https://bursa-binelui.staging.heroesof.tech/register should open instead.
- also on lower resolutions there is no spacing between "intră în" and "cont"

![image](https://github.com/code4romania/bursa-binelui/assets/137993344/f0bacf6b-1acc-4610-9bd7-fc8cfb6329d1)

**Comment by anastk-code4** [comment]
already reported previously
