### ISSUE TITLE
[Homepage] Pattern over text

### ISSUE THREAD

**Issue by avasi-code4ro** [code4romania/bursa-binelui#70]
https://bursa-binelui.staging.heroesof.tech/

- The pattern should be placed behind the frame/section as in the Figma file
- The first logo should be changed with the Civic Tech 911 logo
-  "Afla cum aici" should be an active link

![image](https://github.com/code4romania/bursa-binelui/assets/137993344/2b91a08b-6f7a-4cf4-bb0a-45dfe5ae7f70)

**Comment by anastk-code4** [comment]
Duplicate, already issued
