### ISSUE TITLE
[Public Website] Broken link on LogIn Page

### ISSUE THREAD

**Issue by overeha** [code4romania/bursa-binelui#76]
On the LogIn page the Create Account hiperlink in the subtext - "Creeaza cont nou" - does not work
- fix link on "Creeaza cont nou"(should lead to this https://bursa-binelui.staging.heroesof.tech/register)
- leave a space between "Nu ai cont pe Bursa Binelui?" and "Creeaza cont nou"
- 
![image](https://github.com/code4romania/bursa-binelui/assets/45068169/bc95001c-b9a0-48a6-878b-47a2aae61978)

**Comment by FlorinZarafu** [comment]
fixed in previous commits
