### ISSUE TITLE
[Admin ONG] Edit domains does not display correctly - box doesn't expand

### ISSUE THREAD

**Issue by overeha** [code4romania/bursa-binelui#83]
If I want  to edit my domains, the dropdown does not puch the modal container and I cannot work properly to make the selection. 
Modal container should expand. 

![image](https://github.com/code4romania/bursa-binelui/assets/45068169/8052ef09-76d0-48d9-a9cd-6fceb4e7f9e9)

**Comment by FlorinZarafu** [comment]
fixed in previous comits
